### ISSUE TITLE
Issue while activating DDIC objects

### ISSUE THREAD

**Issue by rjbhayani** [DevEpos/abap-db-browser#19]
Hi,

I am facing below issue. am I missing any other dependencies 

![image](https://user-images.githubusercontent.com/19501487/125781098-8311dc67-ce95-4ce5-ac9e-6f25aff6e51b.png)

**Comment by stockbal** [comment]
Hi @rjbhayani,

Please have a look at the [installation instructions](https://github.com/stockbal/abap-db-browser/wiki/Installation). From the screenshot it looks like the standard issue which unfortunately occurs during the first installation.

Regards,
Ludwig

**Comment by rjbhayani** [comment]
Thank you I followed the same and it worked but now only one issue related to activation of class
![image](https://user-images.githubusercontent.com/19501487/125791227-fa67f685-8cf6-46e4-aa09-27fad9891380.png)

**Comment by stockbal** [comment]
Hm,

so the structure which is used should look like the following
![image](https://user-images.githubusercontent.com/35834861/125797002-8b366150-c5e7-4233-8acf-7cf90e1c6f2e.png)
Maybe try to activate it again manually or the with the program `RADMASG0_C3`

**Comment by rjbhayani** [comment]
Thank you , it worked ":)
