### ISSUE TITLE
Cause of installation errors

### ISSUE THREAD

**Issue by mbtools** [DevEpos/abap-db-browser#22]
Ref https://devepos.com/projects/abap-db-browser/installation.html#install-of-dependencies

Hi Ludwig,

I have done a detailed analysis of the installation errors and already made a few corrections to abapGit (for example, https://github.com/abapGit/abapGit/pull/5998, https://github.com/abapGit/abapGit/pull/5989, and various log improvements).

Today, I was able to identify the root cause. The mass DDIC activation fails because of two secondary indexes ([zdbbr_tabf.tabl.xml](https://github.com/stockbal/abap-db-browser/blob/a80d01de72361bf0ea840b9f0b231373cb013514/src/cross/zdbbr_tabf.tabl.xml) and [zdbbr_vardata.tabl.xml](https://github.com/stockbal/abap-db-browser/blob/a80d01de72361bf0ea840b9f0b231373cb013514/src/cross/zdbbr_vardata.tabl.xml)). The mass activation is not able to order the objects properly and tries to activate an index before the include used in the table index is available (see attached log). It looks like a bug in SAP. 

If you remove the indexes or comment out the following lines, your repo installs without errors! 😃 

![image](https://user-images.githubusercontent.com/59966492/213942361-95ea9aeb-8b2a-4ca3-87b2-d57b91981d1a.png)

I will try to create a small example for reproducing the issue which we can then use to create a ticket with SAP and hopefully get a fix. 

Viele Gruesse,
Marc

PS: The new feature ["Advanced > Activate Objects"](https://github.com/abapGit/abapGit/pull/5994) is also quite handy. You can pull, activate, and pull again to install everything without workarounds.

[activation_log.zip](https://github.com/stockbal/abap-db-browser/files/10475608/activation_log.zip)

**Comment by stockbal** [comment]
Hi Marc,

Thanks for the analysis 👌

Best Regards,
Ludwig

**Comment by mbtools** [comment]
Wir brauchen den Index gar nicht in die Aktivierungsqueue aufnehmen :-)

https://github.com/abapGit/abapGit/pull/6055 sollte das Problem loesen.
