### ISSUE TITLE
dump in git during update

### ISSUE THREAD

**Issue by MartinH1337** [DevEpos/abap-db-browser#23]
I updated search tools and ui toolbox, but when I do another pull on abap db browser, git dumps with DBSQL_DUPLICATE_KEY_ERROR.

In the DELETE FROM seocompotx a class name is given, but in the insert it is empty.
![image](https://user-images.githubusercontent.com/92519431/229420341-302e904a-6109-4a0a-8755-d465391e61a2.png)
But I don't know nothing about this...

System version is S/4HANA 2020 FP3, 755,03.

**Comment by stockbal** [comment]
Hi @MartinH1337,

please update to the lastest abapGit version and try again.

Best Regards,
Ludwig

**Comment by MartinH1337** [comment]
Thanks a lot, Ludwig!

Kind regard
Martin
