### ISSUE TITLE
'NULL' expected instead of 'IS INITIAL'

### ISSUE THREAD

**Issue by jaysonwcs** [DevEpos/abap-db-browser#25]
When I try to open a database table on the main ZDBBR tree, it throws a dump.
When I tried to investigate the issue, I found the following syntax error:

![image](https://user-images.githubusercontent.com/7007373/231838295-5a9ba6d5-ad86-4be3-b1c1-b2d5414950a7.png)

Should'nt this be IS NOT NULL?

**Comment by stockbal** [comment]
Hi @jaysonwcs,

No, `IS NOT INITIAL` is syntactically correct. Unfortunately this is only valid starting with NW 7.53 🙈. 

I just made a commit that should fix the issue

Regards, 
Ludwig

**Comment by jaysonwcs** [comment]
Ah, yes. You are correct! My system is NW 7.52.

And thanks for the fix! 😃
