### ISSUE TITLE
Dump Interface component "ZIF_SAT_C_OBJECT_SEARCH~C_SEARCH_OPTION" does not exist.

### ISSUE THREAD

**Issue by christianguenter2** [DevEpos/abap-db-browser#30]
I get this dump when starting transaction ZDBBR. Latest version of dependencies are installed.

![grafik](https://github.com/DevEpos/abap-db-browser/assets/17437789/762a7cbc-0cab-4313-bbae-41dbe5967f2a)
![grafik](https://github.com/DevEpos/abap-db-browser/assets/17437789/63ed6468-5066-4f19-a717-c66caa781ef1)

**Comment by stockbal** [comment]
Hi @christianguenter2,

that's the problem when too many tools are updated at the same time. Some things are just forgotten 😅.
I just merged the required changed due too the updates in [abap-search-tools](https://github.com/DevEpos/abap-search-tools).

Please pull again. It should work now.

Best regards,
Ludwig

**Comment by christianguenter2** [comment]
Thanks for your fast response. It's working again.

Amazing work!
