### ISSUE TITLE
When adding numeric fields, only a small number of numeric fields can be added

### ISSUE THREAD

**Issue by COOPER-DENG** [DevEpos/abap-db-browser#35]
HI, @stockbal 
In the SQL console, it works when wog001 is added to wog009 but it gives an error when wog001 is added to wog010 or even wog016,
Is there a solution?
![Snipaste_2024-09-20_18-45-10](https://github.com/user-attachments/assets/17e49d07-f6d9-4b15-bff6-442eebdd5644)

Best wishs,
Cooper

**Comment by reichr-dev** [comment]
Hi @COOPER-DENG ,

This is an error returned by the database and appears in all places in the SAP system where you can execute a select statement ( ADT SQL Console, ABAP Report ). The reason for the error is that summing up so many amounts with a length of 23 places and 2 decimals may exceed the maximum length for a numeric field 31 places and 14 decimals.

A possible workaround would be to add a cast in the selection, assuming the summed up amount does not have more than 31 places and 14 decimals.

![image](https://github.com/user-attachments/assets/571dde5e-ffe9-44ec-bc9c-fd3c3d3ecc17)

For reference you can find here the discussion in the sap comunity: https://community.sap.com/t5/application-development-discussions/syntax-issue-in-advacne-sql/td-p/508018

Kind regards,
Renata

**Comment by COOPER-DENG** [comment]
> Hi @COOPER-DENG ,
> 
> This is an error returned by the database and appears in all places in the SAP system where you can execute a select statement ( ADT SQL Console, ABAP Report ). The reason for the error is that summing up so many amounts with a length of 23 places and 2 decimals may exceed the maximum length for a numeric field 31 places and 14 decimals.
> 
> A possible workaround would be to add a cast in the selection, assuming the summed up amount does not have more than 31 places and 14 decimals.
> 
> ![image](https://private-user-images.githubusercontent.com/77360310/369705959-571dde5e-ffe9-44ec-bc9c-fd3c3d3ecc17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzA5NDUsIm5iZiI6MTcyNzIzMDY0NSwicGF0aCI6Ii83NzM2MDMxMC8zNjk3MDU5NTktNTcxZGRlNWUtZmZlOS00NGVjLWJjOWMtZmQzYzNkM2VjYzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDAyMTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjNhZGEyYjc0OGJjMGZjZTY5Y2UxZjVlYzUzYTZjMjY4NDhlNzA5ZmNlODY3MzJiYTQ1YmI5YTkwOTRmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6qcfPMBcf-THBc7CEI1RU9bxg1yz8nl-O5Wi0Z7VY0A)
> 
> For reference you can find here the discussion in the sap comunity: https://community.sap.com/t5/application-development-discussions/syntax-issue-in-advacne-sql/td-p/508018
> 
> Kind regards, Renata

HI,@
You are right, I have solved the problem according to the method you provided, thank you!

> Hi @COOPER-DENG ,
> 
> This is an error returned by the database and appears in all places in the SAP system where you can execute a select statement ( ADT SQL Console, ABAP Report ). The reason for the error is that summing up so many amounts with a length of 23 places and 2 decimals may exceed the maximum length for a numeric field 31 places and 14 decimals.
> 
> A possible workaround would be to add a cast in the selection, assuming the summed up amount does not have more than 31 places and 14 decimals.
> 
> ![image](https://private-user-images.githubusercontent.com/77360310/369705959-571dde5e-ffe9-44ec-bc9c-fd3c3d3ecc17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzA5NDUsIm5iZiI6MTcyNzIzMDY0NSwicGF0aCI6Ii83NzM2MDMxMC8zNjk3MDU5NTktNTcxZGRlNWUtZmZlOS00NGVjLWJjOWMtZmQzYzNkM2VjYzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDAyMTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjNhZGEyYjc0OGJjMGZjZTY5Y2UxZjVlYzUzYTZjMjY4NDhlNzA5ZmNlODY3MzJiYTQ1YmI5YTkwOTRmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6qcfPMBcf-THBc7CEI1RU9bxg1yz8nl-O5Wi0Z7VY0A)
> 
> For reference you can find here the discussion in the sap comunity: https://community.sap.com/t5/application-development-discussions/syntax-issue-in-advacne-sql/td-p/508018
> 
> Kind regards, Renata

Hi, @reichr-dev ,

You are right, I have solved the problem according to the method you provided, thank you!

 Best regards,
 Cooper
